version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pc_store_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      # Esto inicializa la BD automáticamente con nuestros scripts
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pc_store_cli
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    stdin_open: true # Necesario para interactuar con el menú
    tty: true # Necesario para interactuar con el menú

volumes:
  postgres_data:
